using GhostCursorSharp.Internal;
using PuppeteerSharp;

namespace GhostCursorSharp;

/// <summary>
/// Moves a Puppeteer mouse along human-like paths generated by <see cref="CursorPath"/>.
/// </summary>
public sealed class GhostCursor
{
    private readonly GhostCursorElementLocator _elementLocator;
    private readonly GhostCursorMover _mover;
    private readonly GhostCursorOptionResolver _optionResolver;
    private readonly GhostCursorScroller _scroller;
    private readonly GhostCursorState _state;
    private MouseHelperInstallation? _mouseHelper;

    /// <summary>
    /// Initializes a new instance of the <see cref="GhostCursor"/> class.
    /// </summary>
    /// <param name="page">The Puppeteer page whose mouse will be controlled.</param>
    /// <param name="start">The initial cursor location. Defaults to the origin.</param>
    public GhostCursor(IPage page, Vector? start = null)
        : this(page, new GhostCursorOptions { Start = start })
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="GhostCursor"/> class.
    /// </summary>
    /// <param name="page">The Puppeteer page whose mouse will be controlled.</param>
    /// <param name="options">The optional cursor configuration.</param>
    public GhostCursor(IPage page, GhostCursorOptions? options)
    {
        _state = new GhostCursorState(page, options?.Start ?? Vector.Origin);
        DefaultOptions = options?.DefaultOptions;

        _optionResolver = new GhostCursorOptionResolver(() => DefaultOptions);
        _elementLocator = new GhostCursorElementLocator(page);
        _scroller = new GhostCursorScroller(_state);
        _mover = new GhostCursorMover(_state, _scroller);

        if (options?.Visible == true)
        {
            _ = InstallMouseHelperAsync();
        }
    }

    /// <summary>
    /// Gets the Puppeteer page controlled by this cursor.
    /// </summary>
    public IPage Page => _state.Page;

    /// <summary>
    /// Gets or sets the default options applied to cursor actions.
    /// </summary>
    public DefaultOptions? DefaultOptions { get; set; }

    /// <summary>
    /// Gets the current cursor location tracked by this instance.
    /// </summary>
    public Vector Location => _state.Location;

    /// <summary>
    /// Creates a cursor using a compatibility-oriented factory method.
    /// </summary>
    /// <param name="page">The Puppeteer page whose mouse will be controlled.</param>
    /// <param name="start">The initial cursor location. Defaults to the origin.</param>
    /// <param name="defaultOptions">The default options applied to actions created by this cursor.</param>
    /// <param name="visible">Whether the visual mouse helper should be installed immediately.</param>
    /// <returns>A configured <see cref="GhostCursor"/> instance.</returns>
    public static GhostCursor CreateCursor(
        IPage page,
        Vector? start = null,
        DefaultOptions? defaultOptions = null,
        bool visible = false)
        => new(page, new GhostCursorOptions
        {
            Start = start,
            DefaultOptions = defaultOptions,
            Visible = visible
        });

    /// <summary>
    /// Installs the visual mouse helper into the current page and future navigations.
    /// </summary>
    /// <returns>An installation handle that can later remove the helper.</returns>
    public async Task<MouseHelperInstallation> InstallMouseHelperAsync()
    {
        if (_mouseHelper is not null)
        {
            return _mouseHelper;
        }

        _mouseHelper = await MouseHelper.InstallAsync(Page);
        return _mouseHelper;
    }

    /// <summary>
    /// Removes the visual mouse helper if it is currently installed.
    /// </summary>
    /// <returns>A task that completes when the helper has been removed.</returns>
    public async Task RemoveMouseHelperAsync()
    {
        if (_mouseHelper is null)
        {
            return;
        }

        await _mouseHelper.RemoveAsync();
        _mouseHelper = null;
    }

    /// <summary>
    /// Gets the current cursor location.
    /// </summary>
    /// <returns>The current cursor location.</returns>
    public Vector GetLocation()
        => Location;

    /// <summary>
    /// Resolves the first element matching the selector.
    /// </summary>
    /// <param name="selector">The selector to query. XPath selectors are also supported.</param>
    /// <param name="options">Optional selector wait settings.</param>
    /// <returns>The resolved element handle.</returns>
    /// <exception cref="InvalidOperationException">Thrown when the selector does not resolve to an element.</exception>
    public Task<IElementHandle> GetElementAsync(string selector, GetElementOptions? options = null)
        => _elementLocator.GetElementAsync(selector, _optionResolver.ResolveGetElementOptions(options));

    /// <summary>
    /// Scrolls the first matching element into view if needed.
    /// </summary>
    /// <param name="selector">The selector to query. XPath selectors are also supported.</param>
    /// <param name="options">Optional scroll settings.</param>
    /// <returns>A task that completes when the element is in view.</returns>
    public async Task ScrollIntoViewAsync(string selector, ScrollIntoViewOptions? options = null)
    {
        var resolvedOptions = _optionResolver.ResolveScrollIntoViewOptions(options);
        var element = await _elementLocator.GetElementAsync(
            selector,
            new ResolvedGetElementOptions(resolvedOptions.WaitForSelector));

        await _scroller.ScrollIntoViewAsync(element, resolvedOptions);
    }

    /// <summary>
    /// Scrolls the specified element into view if needed.
    /// </summary>
    /// <param name="element">The element to ensure is visible.</param>
    /// <param name="options">Optional scroll settings.</param>
    /// <returns>A task that completes when the element is in view.</returns>
    public Task ScrollIntoViewAsync(IElementHandle element, ScrollIntoViewOptions? options = null)
        => _scroller.ScrollIntoViewAsync(element, _optionResolver.ResolveScrollIntoViewOptions(options));

    /// <summary>
    /// Scrolls the page by the specified delta.
    /// </summary>
    /// <param name="delta">The horizontal and vertical document deltas to apply.</param>
    /// <param name="options">Optional scroll settings.</param>
    /// <returns>A task that completes when scrolling finishes.</returns>
    public Task ScrollAsync(Vector delta, ScrollOptions? options = null)
        => _scroller.ScrollAsync(delta, _optionResolver.ResolveScrollOptions(options));

    /// <summary>
    /// Scrolls to a named document boundary.
    /// </summary>
    /// <param name="destination">One of <c>top</c>, <c>bottom</c>, <c>left</c>, or <c>right</c>.</param>
    /// <param name="options">Optional scroll settings.</param>
    /// <returns>A task that completes when scrolling finishes.</returns>
    /// <exception cref="ArgumentException">Thrown when the named destination is not recognized.</exception>
    public Task ScrollToAsync(string destination, ScrollOptions? options = null)
        => _scroller.ScrollToAsync(destination, _optionResolver.ResolveScrollOptions(options));

    /// <summary>
    /// Scrolls to the specified document coordinates.
    /// </summary>
    /// <param name="destination">The target document coordinates.</param>
    /// <param name="options">Optional scroll settings.</param>
    /// <returns>A task that completes when scrolling finishes.</returns>
    public Task ScrollToAsync(ScrollToDestination destination, ScrollOptions? options = null)
        => _scroller.ScrollToAsync(destination, _optionResolver.ResolveScrollOptions(options));

    /// <summary>
    /// Moves the cursor to the specified destination using a generated human-like path.
    /// </summary>
    /// <param name="destination">The destination coordinate.</param>
    /// <param name="pathOptions">Optional path generation settings.</param>
    /// <param name="delayPerStep">An optional delay in milliseconds between path points.</param>
    /// <returns>A task that completes when the movement finishes.</returns>
    public Task MoveToAsync(Vector destination, PathOptions? pathOptions = null, int delayPerStep = 0)
        => _mover.MoveToAsync(destination, pathOptions, delayPerStep);

    /// <summary>
    /// Moves the cursor by the specified delta using a generated human-like path.
    /// </summary>
    /// <param name="delta">The relative movement delta.</param>
    /// <param name="pathOptions">Optional path generation settings.</param>
    /// <param name="delayPerStep">An optional delay in milliseconds between path points.</param>
    /// <returns>A task that completes when the movement finishes.</returns>
    public Task MoveByAsync(Vector delta, PathOptions? pathOptions = null, int delayPerStep = 0)
        => _mover.MoveByAsync(delta, pathOptions, delayPerStep);

    /// <summary>
    /// Moves the cursor to a point selected inside the specified bounding box.
    /// </summary>
    /// <param name="boundingBox">The bounding box to target.</param>
    /// <param name="options">Optional movement and targeting settings.</param>
    /// <returns>A task that completes when the movement finishes.</returns>
    public async Task MoveAsync(BoundingBox boundingBox, MoveOptions? options = null)
    {
        var resolvedOptions = _optionResolver.ResolveMoveOptions(options);
        await _mover.MoveAsync(boundingBox, resolvedOptions);
        await GhostCursorTiming.DelayAsync(resolvedOptions.MoveDelay, resolvedOptions.RandomizeMoveDelay);
    }

    /// <summary>
    /// Moves the cursor to a point selected inside the specified element.
    /// </summary>
    /// <param name="element">The element to target.</param>
    /// <param name="options">Optional movement and targeting settings.</param>
    /// <returns>A task that completes when the movement finishes.</returns>
    /// <exception cref="InvalidOperationException">Thrown when the element bounds cannot be determined.</exception>
    public async Task MoveAsync(IElementHandle element, MoveOptions? options = null)
    {
        var resolvedOptions = _optionResolver.ResolveMoveOptions(options);
        await _mover.MoveAsync(element, resolvedOptions);
        await GhostCursorTiming.DelayAsync(resolvedOptions.MoveDelay, resolvedOptions.RandomizeMoveDelay);
    }

    /// <summary>
    /// Moves the cursor to a point selected inside the first element matching the selector.
    /// </summary>
    /// <param name="selector">The selector to query. XPath selectors are also supported.</param>
    /// <param name="options">Optional movement and targeting settings.</param>
    /// <returns>A task that completes when the movement finishes.</returns>
    public async Task MoveAsync(string selector, MoveOptions? options = null)
    {
        var resolvedOptions = _optionResolver.ResolveMoveOptions(options);
        var element = await _elementLocator.GetElementAsync(
            selector,
            new ResolvedGetElementOptions(resolvedOptions.WaitForSelector));

        await _mover.MoveAsync(element, resolvedOptions);
        await GhostCursorTiming.DelayAsync(resolvedOptions.MoveDelay, resolvedOptions.RandomizeMoveDelay);
    }

    /// <summary>
    /// Presses the configured mouse button at the current cursor location.
    /// </summary>
    /// <param name="options">Optional click settings.</param>
    /// <returns>A task that completes when the button has been pressed.</returns>
    public Task MouseDownAsync(ClickOptions? options = null)
        => _mover.MouseDownAsync(_optionResolver.ResolveClickOptions(options));

    /// <summary>
    /// Releases the configured mouse button at the current cursor location.
    /// </summary>
    /// <param name="options">Optional click settings.</param>
    /// <returns>A task that completes when the button has been released.</returns>
    public Task MouseUpAsync(ClickOptions? options = null)
        => _mover.MouseUpAsync(_optionResolver.ResolveClickOptions(options));

    /// <summary>
    /// Clicks at the current cursor location.
    /// </summary>
    /// <param name="options">Optional click settings.</param>
    /// <returns>A task that completes when the click finishes.</returns>
    public Task ClickAsync(ClickOptions? options = null)
        => _mover.ClickAsync(_optionResolver.ResolveClickOptions(options));

    /// <summary>
    /// Moves to the specified element selector and clicks inside it.
    /// </summary>
    /// <param name="selector">The selector to query. XPath selectors are also supported.</param>
    /// <param name="options">Optional click settings.</param>
    /// <returns>A task that completes when the click finishes.</returns>
    public async Task ClickAsync(string selector, ClickOptions? options = null)
    {
        var resolvedOptions = _optionResolver.ResolveClickOptions(options);
        var element = await _elementLocator.GetElementAsync(
            selector,
            new ResolvedGetElementOptions(resolvedOptions.WaitForSelector));

        await _mover.MoveAsync(element, resolvedOptions);
        await _mover.ClickAsync(resolvedOptions);
    }

    /// <summary>
    /// Moves to the specified element and clicks inside it.
    /// </summary>
    /// <param name="element">The element to target.</param>
    /// <param name="options">Optional click settings.</param>
    /// <returns>A task that completes when the click finishes.</returns>
    public async Task ClickAsync(IElementHandle element, ClickOptions? options = null)
    {
        var resolvedOptions = _optionResolver.ResolveClickOptions(options);
        await _mover.MoveAsync(element, resolvedOptions);
        await _mover.ClickAsync(resolvedOptions);
    }
}
