using PuppeteerSharp;
using PuppeteerSharp.Input;

namespace GhostCursorSharp;

/// <summary>
/// Moves a Puppeteer mouse along human-like paths generated by <see cref="CursorPath"/>.
/// </summary>
public sealed class GhostCursor
{
    private readonly IPage _page;
    private MouseHelperInstallation? _mouseHelper;

    /// <summary>
    /// Initializes a new instance of the <see cref="GhostCursor"/> class.
    /// </summary>
    /// <param name="page">The Puppeteer page whose mouse will be controlled.</param>
    /// <param name="start">The initial cursor location. Defaults to the origin.</param>
    public GhostCursor(IPage page, Vector? start = null)
    {
        _page = page;
        Location = start ?? Vector.Origin;
    }

    /// <summary>
    /// Gets the current cursor location tracked by this instance.
    /// </summary>
    public Vector Location { get; private set; }

    /// <summary>
    /// Installs the visual mouse helper into the current page and future navigations.
    /// </summary>
    /// <returns>An installation handle that can later remove the helper.</returns>
    public async Task<MouseHelperInstallation> InstallMouseHelperAsync()
    {
        if (_mouseHelper is not null)
        {
            return _mouseHelper;
        }

        _mouseHelper = await MouseHelper.InstallAsync(_page);
        return _mouseHelper;
    }

    /// <summary>
    /// Removes the visual mouse helper if it is currently installed.
    /// </summary>
    /// <returns>A task that completes when the helper has been removed.</returns>
    public async Task RemoveMouseHelperAsync()
    {
        if (_mouseHelper is null)
        {
            return;
        }

        await _mouseHelper.RemoveAsync();
        _mouseHelper = null;
    }

    /// <summary>
    /// Moves the cursor to the specified destination using a generated human-like path.
    /// </summary>
    /// <param name="destination">The destination coordinate.</param>
    /// <param name="pathOptions">Optional path generation settings.</param>
    /// <param name="delayPerStep">An optional delay in milliseconds between path points.</param>
    /// <returns>A task that completes when the movement finishes.</returns>
    public async Task MoveToAsync(Vector destination, PathOptions? pathOptions = null, int delayPerStep = 0)
    {
        var path = CursorPath.Generate(Location, destination, pathOptions);

        foreach (var point in path)
        {
            await _page.Mouse.MoveAsync(
                Convert.ToDecimal(point.X),
                Convert.ToDecimal(point.Y),
                new PuppeteerSharp.Input.MoveOptions { Steps = 1 });

            Location = point;

            if (delayPerStep > 0)
            {
                await Task.Delay(delayPerStep);
            }
        }
    }

    /// <summary>
    /// Moves the cursor by the specified delta using a generated human-like path.
    /// </summary>
    /// <param name="delta">The relative movement delta.</param>
    /// <param name="pathOptions">Optional path generation settings.</param>
    /// <param name="delayPerStep">An optional delay in milliseconds between path points.</param>
    /// <returns>A task that completes when the movement finishes.</returns>
    public Task MoveByAsync(Vector delta, PathOptions? pathOptions = null, int delayPerStep = 0)
        => MoveToAsync(new Vector(Location.X + delta.X, Location.Y + delta.Y), pathOptions, delayPerStep);

    /// <summary>
    /// Moves the cursor to a point selected inside the specified bounding box.
    /// </summary>
    /// <param name="boundingBox">The bounding box to target.</param>
    /// <param name="options">Optional movement and targeting settings.</param>
    /// <returns>A task that completes when the movement finishes.</returns>
    public Task MoveAsync(BoundingBox boundingBox, MoveOptions? options = null)
    {
        var destination = CursorTargeting.GetPointInBox(boundingBox, options);
        var pathOptions = new PathOptions
        {
            MoveSpeed = options?.MoveSpeed,
            SpreadOverride = options?.SpreadOverride
        };

        return MoveToAsync(destination, pathOptions, options?.DelayPerStep ?? 0);
    }

    /// <summary>
    /// Moves the cursor to a point selected inside the specified element.
    /// </summary>
    /// <param name="element">The element to target.</param>
    /// <param name="options">Optional movement and targeting settings.</param>
    /// <returns>A task that completes when the movement finishes.</returns>
    /// <exception cref="InvalidOperationException">Thrown when the element bounds cannot be determined.</exception>
    public async Task MoveAsync(IElementHandle element, MoveOptions? options = null)
    {
        var boundingBox = await element.BoundingBoxAsync()
            ?? throw new InvalidOperationException("Could not determine the element bounds.");

        await MoveAsync(boundingBox, options);
    }

    /// <summary>
    /// Moves the cursor to a point selected inside the first element matching the selector.
    /// </summary>
    /// <param name="selector">The selector to query.</param>
    /// <param name="options">Optional movement and targeting settings.</param>
    /// <returns>A task that completes when the movement finishes.</returns>
    /// <exception cref="InvalidOperationException">Thrown when the selector cannot be resolved to an element.</exception>
    public async Task MoveAsync(string selector, MoveOptions? options = null)
    {
        var element = await _page.QuerySelectorAsync(selector)
            ?? throw new InvalidOperationException($"Could not find element with selector '{selector}'.");

        await MoveAsync(element, options);
    }
}
