using GhostCursorSharp.Internal;
using PlaywrightBoundingBox = Microsoft.Playwright.ElementHandleBoundingBoxResult;
using PlaywrightElementHandle = Microsoft.Playwright.IElementHandle;
using PlaywrightPage = Microsoft.Playwright.IPage;

namespace GhostCursorSharp;

/// <summary>
/// Moves a Playwright mouse along human-like paths generated by <see cref="CursorPath"/>.
/// </summary>
public sealed class PlaywrightGhostCursor
{
    private readonly GhostCursorElementLocator _elementLocator;
    private readonly ICursorElementGeometry _geometry;
    private readonly GhostCursorMover _mover;
    private readonly GhostCursorOptionResolver _optionResolver;
    private readonly PlaywrightPage _page;
    private readonly GhostCursorRandomMover _randomMover;
    private readonly GhostCursorScroller _scroller;
    private readonly GhostCursorState _state;
    private MouseHelperInstallation? _mouseHelper;

    /// <summary>
    /// Initializes a new instance of the <see cref="PlaywrightGhostCursor"/> class.
    /// </summary>
    /// <param name="page">The Playwright page whose mouse will be controlled.</param>
    /// <param name="start">The initial cursor location. Defaults to the origin.</param>
    public PlaywrightGhostCursor(PlaywrightPage page, Vector? start = null)
        : this(page, new GhostCursorOptions { Start = start })
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="PlaywrightGhostCursor"/> class.
    /// </summary>
    /// <param name="page">The Playwright page whose mouse will be controlled.</param>
    /// <param name="options">The optional cursor configuration.</param>
    public PlaywrightGhostCursor(PlaywrightPage page, GhostCursorOptions? options)
    {
        _page = page;
        var pageAdapter = new PlaywrightCursorPageAdapter(page);
        _state = new GhostCursorState(pageAdapter, options?.Start ?? Vector.Origin);
        DefaultOptions = options?.DefaultOptions;

        _optionResolver = new GhostCursorOptionResolver(() => DefaultOptions);
        _elementLocator = new GhostCursorElementLocator(pageAdapter);
        _geometry = new PlaywrightCursorElementGeometry();
        _scroller = new GhostCursorScroller(_state, _geometry);
        _mover = new GhostCursorMover(_state, _scroller, _geometry);
        _randomMover = new GhostCursorRandomMover(_state, _mover, _scroller, _optionResolver);

        if (options?.Visible == true)
        {
            _ = InstallMouseHelperAsync();
        }

        if (options?.PerformRandomMoves == true)
        {
            _randomMover.Toggle(true);
        }
    }

    /// <summary>
    /// Gets the Playwright page controlled by this cursor.
    /// </summary>
    public PlaywrightPage Page => _page;

    /// <summary>
    /// Gets or sets the default options applied to cursor actions.
    /// </summary>
    public DefaultOptions? DefaultOptions { get; set; }

    /// <summary>
    /// Gets the current cursor location tracked by this instance.
    /// </summary>
    public Vector Location => _state.Location;

    /// <summary>
    /// Creates a cursor using a compatibility-oriented factory method.
    /// </summary>
    /// <param name="page">The Playwright page whose mouse will be controlled.</param>
    /// <param name="start">The initial cursor location. Defaults to the origin.</param>
    /// <param name="defaultOptions">The default options applied to actions created by this cursor.</param>
    /// <param name="visible">Whether the visual mouse helper should be installed immediately.</param>
    /// <returns>A configured <see cref="PlaywrightGhostCursor"/> instance.</returns>
    public static PlaywrightGhostCursor CreateCursor(
        PlaywrightPage page,
        Vector? start = null,
        DefaultOptions? defaultOptions = null,
        bool visible = false)
        => new(page, new GhostCursorOptions
        {
            Start = start,
            DefaultOptions = defaultOptions,
            Visible = visible
        });

    /// <summary>
    /// Creates a cursor using a compatibility-oriented factory method with initial random movement support.
    /// </summary>
    /// <param name="page">The Playwright page whose mouse will be controlled.</param>
    /// <param name="start">The initial cursor location. Defaults to the origin.</param>
    /// <param name="performRandomMoves">Whether background random mouse movements should start immediately.</param>
    /// <param name="defaultOptions">The default options applied to actions created by this cursor.</param>
    /// <param name="visible">Whether the visual mouse helper should be installed immediately.</param>
    /// <returns>A configured <see cref="PlaywrightGhostCursor"/> instance.</returns>
    public static PlaywrightGhostCursor CreateCursor(
        PlaywrightPage page,
        Vector? start,
        bool performRandomMoves,
        DefaultOptions? defaultOptions = null,
        bool visible = false)
        => new(page, new GhostCursorOptions
        {
            Start = start,
            PerformRandomMoves = performRandomMoves,
            DefaultOptions = defaultOptions,
            Visible = visible
        });

    /// <summary>
    /// Installs the visual mouse helper into the current page and future navigations.
    /// </summary>
    /// <returns>An installation handle that can later remove the helper.</returns>
    public async Task<MouseHelperInstallation> InstallMouseHelperAsync()
    {
        if (_mouseHelper is not null)
        {
            return _mouseHelper;
        }

        _mouseHelper = await MouseHelper.InstallAsync(Page);
        return _mouseHelper;
    }

    /// <summary>
    /// Removes the visual mouse helper if it is currently installed.
    /// </summary>
    /// <returns>A task that completes when the helper has been removed.</returns>
    public async Task RemoveMouseHelperAsync()
    {
        if (_mouseHelper is null)
        {
            return;
        }

        await _mouseHelper.RemoveAsync();
        _mouseHelper = null;
    }

    /// <summary>
    /// Gets the current cursor location.
    /// </summary>
    /// <returns>The current cursor location.</returns>
    public Vector GetLocation()
        => Location;

    /// <summary>
    /// Toggles background random cursor movement on or off.
    /// </summary>
    /// <param name="random">When <see langword="true"/>, enable random movement; otherwise disable it.</param>
    public void ToggleRandomMove(bool random)
        => _randomMover.Toggle(random);

    /// <summary>
    /// Resolves the first element matching the selector.
    /// </summary>
    /// <param name="selector">The selector to query. XPath selectors are also supported.</param>
    /// <param name="options">Optional selector wait settings.</param>
    /// <returns>The resolved element handle.</returns>
    /// <exception cref="InvalidOperationException">Thrown when the selector does not resolve to an element.</exception>
    public async Task<PlaywrightElementHandle> GetElementAsync(string selector, GetElementOptions? options = null)
        => Unwrap(await _elementLocator.GetElementAsync(selector, _optionResolver.ResolveGetElementOptions(options)));

    /// <summary>
    /// Returns the provided element handle unchanged.
    /// </summary>
    /// <param name="element">The existing element handle.</param>
    /// <param name="options">Optional selector wait settings. Ignored when a handle is already provided.</param>
    /// <returns>The same <paramref name="element"/> instance.</returns>
    public Task<PlaywrightElementHandle> GetElementAsync(PlaywrightElementHandle element, GetElementOptions? options = null)
    {
        _ = _optionResolver.ResolveGetElementOptions(options);
        return Task.FromResult(element);
    }

    /// <summary>
    /// Resolves the element box using the same geometry fallbacks used by cursor movement.
    /// </summary>
    /// <param name="element">The element whose box should be resolved.</param>
    /// <param name="relativeToMainFrame">
    /// When <see langword="true"/>, return coordinates relative to the main frame; otherwise adjust child-frame boxes.
    /// </param>
    /// <returns>The resolved element box.</returns>
    public async Task<PlaywrightBoundingBox> GetElementBoxAsync(PlaywrightElementHandle element, bool relativeToMainFrame = true)
    {
        var box = await _geometry.GetElementBoxAsync(Wrap(element), relativeToMainFrame);
        return ToPlaywrightBoundingBox(box);
    }

    /// <summary>
    /// Scrolls the first matching element into view if needed.
    /// </summary>
    /// <param name="selector">The selector to query. XPath selectors are also supported.</param>
    /// <param name="options">Optional scroll settings.</param>
    /// <returns>A task that completes when the element is in view.</returns>
    public async Task ScrollIntoViewAsync(string selector, ScrollIntoViewOptions? options = null)
    {
        var resolvedOptions = _optionResolver.ResolveScrollIntoViewOptions(options);
        await ExecuteActionAsync(async () =>
        {
            var element = await _elementLocator.GetElementAsync(
                selector,
                new ResolvedGetElementOptions(resolvedOptions.WaitForSelector));

            await _scroller.ScrollIntoViewAsync(element, resolvedOptions);
        });
    }

    /// <summary>
    /// Scrolls the specified element into view if needed.
    /// </summary>
    /// <param name="element">The element to ensure is visible.</param>
    /// <param name="options">Optional scroll settings.</param>
    /// <returns>A task that completes when the element is in view.</returns>
    public Task ScrollIntoViewAsync(PlaywrightElementHandle element, ScrollIntoViewOptions? options = null)
        => ExecuteActionAsync(() => _scroller.ScrollIntoViewAsync(Wrap(element), _optionResolver.ResolveScrollIntoViewOptions(options)));

    /// <summary>
    /// Scrolls the page by the specified delta.
    /// </summary>
    /// <param name="delta">The horizontal and vertical document deltas to apply.</param>
    /// <param name="options">Optional scroll settings.</param>
    /// <returns>A task that completes when scrolling finishes.</returns>
    public Task ScrollAsync(Vector delta, ScrollOptions? options = null)
        => ExecuteActionAsync(() => _scroller.ScrollAsync(delta, _optionResolver.ResolveScrollOptions(options)));

    /// <summary>
    /// Scrolls to a named document boundary.
    /// </summary>
    /// <param name="destination">One of <c>top</c>, <c>bottom</c>, <c>left</c>, or <c>right</c>.</param>
    /// <param name="options">Optional scroll settings.</param>
    /// <returns>A task that completes when scrolling finishes.</returns>
    public Task ScrollToAsync(string destination, ScrollOptions? options = null)
        => ExecuteActionAsync(() => _scroller.ScrollToAsync(destination, _optionResolver.ResolveScrollOptions(options)));

    /// <summary>
    /// Scrolls to the specified document coordinates.
    /// </summary>
    /// <param name="destination">The target document coordinates.</param>
    /// <param name="options">Optional scroll settings.</param>
    /// <returns>A task that completes when scrolling finishes.</returns>
    public Task ScrollToAsync(ScrollToDestination destination, ScrollOptions? options = null)
        => ExecuteActionAsync(() => _scroller.ScrollToAsync(destination, _optionResolver.ResolveScrollOptions(options)));

    /// <summary>
    /// Moves the cursor to the specified destination using a generated human-like path.
    /// </summary>
    /// <param name="destination">The destination coordinate.</param>
    /// <param name="pathOptions">Optional path generation settings.</param>
    /// <param name="delayPerStep">An optional delay in milliseconds between path points.</param>
    /// <returns>A task that completes when the movement finishes.</returns>
    public Task MoveToAsync(Vector destination, PathOptions? pathOptions = null, int delayPerStep = 0)
    {
        var resolvedOptions = _optionResolver.ResolveMoveToOptions(null);

        return ExecuteActionAsync(
            () => _mover.MoveToWithAbortAsync(
                destination,
                new PathOptions
                {
                    MoveSpeed = pathOptions?.MoveSpeed ?? resolvedOptions.MoveSpeed,
                    SpreadOverride = pathOptions?.SpreadOverride ?? resolvedOptions.SpreadOverride
                },
                delayPerStep == 0 ? resolvedOptions.DelayPerStep : delayPerStep,
                null),
            async () => await GhostCursorTiming.DelayAsync(
                resolvedOptions.MoveDelay,
                resolvedOptions.RandomizeMoveDelay));
    }

    /// <summary>
    /// Moves the cursor to the specified destination using move-to action options.
    /// </summary>
    /// <param name="destination">The destination coordinate.</param>
    /// <param name="options">Optional move-to settings.</param>
    /// <returns>A task that completes when the movement finishes.</returns>
    public Task MoveToAsync(Vector destination, MoveToOptions? options)
    {
        var resolvedOptions = _optionResolver.ResolveMoveToOptions(options);
        return ExecuteActionAsync(
            () => _mover.MoveToWithAbortAsync(
                destination,
                new PathOptions
                {
                    MoveSpeed = resolvedOptions.MoveSpeed,
                    SpreadOverride = resolvedOptions.SpreadOverride
                },
                resolvedOptions.DelayPerStep,
                null),
            async () => await GhostCursorTiming.DelayAsync(resolvedOptions.MoveDelay, resolvedOptions.RandomizeMoveDelay));
    }

    /// <summary>
    /// Moves the cursor by the specified delta using a generated human-like path.
    /// </summary>
    /// <param name="delta">The relative movement delta.</param>
    /// <param name="pathOptions">Optional path generation settings.</param>
    /// <param name="delayPerStep">An optional delay in milliseconds between path points.</param>
    /// <returns>A task that completes when the movement finishes.</returns>
    public Task MoveByAsync(Vector delta, PathOptions? pathOptions = null, int delayPerStep = 0)
    {
        var resolvedOptions = _optionResolver.ResolveMoveToOptions(null);

        return ExecuteActionAsync(
            () => _mover.MoveByWithAbortAsync(
                delta,
                new PathOptions
                {
                    MoveSpeed = pathOptions?.MoveSpeed ?? resolvedOptions.MoveSpeed,
                    SpreadOverride = pathOptions?.SpreadOverride ?? resolvedOptions.SpreadOverride
                },
                delayPerStep == 0 ? resolvedOptions.DelayPerStep : delayPerStep,
                null),
            async () => await GhostCursorTiming.DelayAsync(
                resolvedOptions.MoveDelay,
                resolvedOptions.RandomizeMoveDelay));
    }

    /// <summary>
    /// Moves the cursor by the specified delta using move-to action options.
    /// </summary>
    /// <param name="delta">The relative movement delta.</param>
    /// <param name="options">Optional move-to settings.</param>
    /// <returns>A task that completes when the movement finishes.</returns>
    public Task MoveByAsync(Vector delta, MoveToOptions? options)
    {
        var resolvedOptions = _optionResolver.ResolveMoveToOptions(options);
        return ExecuteActionAsync(
            () => _mover.MoveByWithAbortAsync(
                delta,
                new PathOptions
                {
                    MoveSpeed = resolvedOptions.MoveSpeed,
                    SpreadOverride = resolvedOptions.SpreadOverride
                },
                resolvedOptions.DelayPerStep,
                null),
            async () => await GhostCursorTiming.DelayAsync(resolvedOptions.MoveDelay, resolvedOptions.RandomizeMoveDelay));
    }

    /// <summary>
    /// Moves the cursor to a point selected inside the specified bounding box.
    /// </summary>
    /// <param name="boundingBox">The bounding box to target.</param>
    /// <param name="options">Optional movement and targeting settings.</param>
    /// <returns>A task that completes when the movement finishes.</returns>
    public async Task MoveAsync(PlaywrightBoundingBox boundingBox, MoveOptions? options = null)
    {
        var resolvedOptions = _optionResolver.ResolveMoveOptions(options);
        await ExecuteActionAsync(
            async () => await _mover.MoveAsync(ToPuppeteerBoundingBox(boundingBox), resolvedOptions),
            async () => await GhostCursorTiming.DelayAsync(resolvedOptions.MoveDelay, resolvedOptions.RandomizeMoveDelay));
    }

    /// <summary>
    /// Moves the cursor to a point selected inside the specified element.
    /// </summary>
    /// <param name="element">The element to target.</param>
    /// <param name="options">Optional movement and targeting settings.</param>
    /// <returns>A task that completes when the movement finishes.</returns>
    public async Task MoveAsync(PlaywrightElementHandle element, MoveOptions? options = null)
    {
        var resolvedOptions = _optionResolver.ResolveMoveOptions(options);
        await ExecuteActionAsync(
            async () => await _mover.MoveAsync(Wrap(element), resolvedOptions),
            async () => await GhostCursorTiming.DelayAsync(resolvedOptions.MoveDelay, resolvedOptions.RandomizeMoveDelay));
    }

    /// <summary>
    /// Moves the cursor to a point selected inside the first element matching the selector.
    /// </summary>
    /// <param name="selector">The selector to query. XPath selectors are also supported.</param>
    /// <param name="options">Optional movement and targeting settings.</param>
    /// <returns>A task that completes when the movement finishes.</returns>
    public async Task MoveAsync(string selector, MoveOptions? options = null)
    {
        var resolvedOptions = _optionResolver.ResolveMoveOptions(options);
        await ExecuteActionAsync(async () =>
        {
            await _mover.MoveAsync(
                () => _elementLocator.GetElementAsync(
                    selector,
                    new ResolvedGetElementOptions(resolvedOptions.WaitForSelector)),
                resolvedOptions);
        },
        async () => await GhostCursorTiming.DelayAsync(resolvedOptions.MoveDelay, resolvedOptions.RandomizeMoveDelay));
    }

    /// <summary>
    /// Presses the configured mouse button at the current cursor location.
    /// </summary>
    /// <param name="options">Optional click settings.</param>
    /// <returns>A task that completes when the button has been pressed.</returns>
    public Task MouseDownAsync(ClickOptions? options = null)
        => ExecuteActionAsync(() => _mover.MouseDownAsync(_optionResolver.ResolveClickOptions(options)));

    /// <summary>
    /// Releases the configured mouse button at the current cursor location.
    /// </summary>
    /// <param name="options">Optional click settings.</param>
    /// <returns>A task that completes when the button has been released.</returns>
    public Task MouseUpAsync(ClickOptions? options = null)
        => ExecuteActionAsync(() => _mover.MouseUpAsync(_optionResolver.ResolveClickOptions(options)));

    /// <summary>
    /// Clicks at the current cursor location.
    /// </summary>
    /// <param name="options">Optional click settings.</param>
    /// <returns>A task that completes when the click finishes.</returns>
    public Task ClickAsync(ClickOptions? options = null)
        => ExecuteActionAsync(() => _mover.ClickAsync(_optionResolver.ResolveClickOptions(options)));

    /// <summary>
    /// Moves to the specified element selector and clicks inside it.
    /// </summary>
    /// <param name="selector">The selector to query. XPath selectors are also supported.</param>
    /// <param name="options">Optional click settings.</param>
    /// <returns>A task that completes when the click finishes.</returns>
    public async Task ClickAsync(string selector, ClickOptions? options = null)
    {
        var resolvedOptions = _optionResolver.ResolveClickOptions(options);
        await ExecuteActionAsync(async () =>
        {
            await _mover.MoveAsync(
                () => _elementLocator.GetElementAsync(
                    selector,
                    new ResolvedGetElementOptions(resolvedOptions.WaitForSelector)),
                resolvedOptions);
            await _mover.ClickAsync(resolvedOptions);
        });
    }

    /// <summary>
    /// Moves to the specified element and clicks inside it.
    /// </summary>
    /// <param name="element">The element to target.</param>
    /// <param name="options">Optional click settings.</param>
    /// <returns>A task that completes when the click finishes.</returns>
    public async Task ClickAsync(PlaywrightElementHandle element, ClickOptions? options = null)
    {
        var resolvedOptions = _optionResolver.ResolveClickOptions(options);
        await ExecuteActionAsync(async () =>
        {
            await _mover.MoveAsync(Wrap(element), resolvedOptions);
            await _mover.ClickAsync(resolvedOptions);
        });
    }

    private static PlaywrightCursorElementHandle Wrap(PlaywrightElementHandle element)
        => new(element);

    private static PlaywrightElementHandle Unwrap(ICursorElementHandle element)
        => element is INativeCursorElementHandle<PlaywrightElementHandle> nativeElement
            ? nativeElement.NativeElement
            : throw new InvalidOperationException(
                $"The {nameof(PlaywrightGhostCursor)} Playwright facade expected a Playwright element adapter.");

    private static PuppeteerSharp.BoundingBox ToPuppeteerBoundingBox(PlaywrightBoundingBox boundingBox)
        => new()
        {
            X = Convert.ToDecimal(boundingBox.X),
            Y = Convert.ToDecimal(boundingBox.Y),
            Width = Convert.ToDecimal(boundingBox.Width),
            Height = Convert.ToDecimal(boundingBox.Height)
        };

    private static PlaywrightBoundingBox ToPlaywrightBoundingBox(PuppeteerSharp.BoundingBox boundingBox)
        => new()
        {
            X = Convert.ToSingle(boundingBox.X),
            Y = Convert.ToSingle(boundingBox.Y),
            Width = Convert.ToSingle(boundingBox.Width),
            Height = Convert.ToSingle(boundingBox.Height)
        };

    private async Task ExecuteActionAsync(Func<Task> action, Func<Task>? afterAction = null)
    {
        using var _ = _state.BeginAction();
        await action();

        if (afterAction is not null)
        {
            await afterAction();
        }
    }
}
