name: .NET Build and Publish NuGet Package

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    # Don't override the version of the package; trust the version in the project file.
    - name: Create NuGet Package
      run: dotnet pack src/GhostCursorSharp/GhostCursorSharp.csproj --output nupkgs --configuration Release

    - name: Upload NuGet Package
      run: dotnet nuget push "nupkgs/*.nupkg" -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
